name: Reuse other workflow

on: [push, workflow_dispatch]

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yaml
    with:
      who-to-greet: '@Willepedia-75'

  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"      
